#!/bin/bash
#
# remove work directory

rm_temp ()
{
  local name="$(basename "$0")"
  if [[ "$name" = "onerpm" ]]; then
    rm -rf $temp_repo
  elif [[ "$name" = "onerpm-pack" ]]; then
    sudo rm -rf $packroot
  fi
}
