#!/bin/bash
#
# remove work directory

rm_temp ()
{
  local name="$(basename "$0")"
  if [[ "$name" = "nekorpm" ]]; then
    rm -rf "$1"
  elif [[ "$name" = "nekorpm-pack" ]]; then
    sudo rm -rf "$1"
  fi
}
