#!/bin/bash

print_package_info ()
{
  echo "-----------------------"
  echo "- Keterangan Aplikasi -"
  printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
  cat "$1"/keterangan
  printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
}

extract_package_info ()
{
  if [ "$2" = "ok" ]; then
    mkdir -p "$3"
    tar -xzf "$1" -C "$3" "keterangan"
  fi
}
