#!/bin/bash

#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#   Copyright (C) La Ode Muh. Fadlun Akbar

# import function here
. /usr/share/nekorpm/functions/cleanup
. /usr/share/nekorpm/functions/download_package
. /usr/share/nekorpm/functions/packaging

# "root_temp" must be declared in the main script
# and assigned with specific directory
root_temp="/tmp/nekorpm-pack-root"
temp="/tmp/nekorpm-pack"

parse_option ()
{
  local arch
  local fedora
  for i in "$@"
  do
  case $i in
      -a=*|--a=*|--arch=*)
      arch="${i#*=}"
      shift # past argument=value
      ;;
      -f=*|--f=*|--fedora=*)
      fedora="${i#*=}"
      shift # past argument=value
      ;;
  esac
  done
  if [[ "$arch" == "" ]]; then
      arch="$(arch)"
  fi
  if [[ "$fedora" == "" ]]; then
      fedora="$(rpm -E %{?fedora})"
  fi
  local package=$@
  main $fedora $arch $package
}

main ()
{
  local fedora=$1
  local arch=$2
  local avail_pkg
  local none_pkg
  local avail_pkg_count=0
  local none_pkg_count=0
  printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' =
  printf "%-20s %-15s %-15s %-15s\n" "  Nama Paket" "Versi Fedora" "Arsitektur" "Ketersediaan"
  printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' =
  shift 2
  for i in $@
  do
    dnf --setopt timeout=0 info $i &> /dev/null
    if [[ $? == 0 ]]; then
      printf "%-20s %-15s %-15s %-15s\n" "  $i" "$fedora" "$arch" "Tersedia"
      avail_pkg+="$i "
      avail_pkg_count=`expr $avail_pkg_count + 1`
    else
      printf "%-20s %-15s %-15s %-15s\n" "  $i" "$fedora" "$arch" "Tidak Tersedia"
      none_pkg+="$i "
      none_pkg_count=`expr $none_pkg_count + 1`
    fi
  done
  printf "\n"
  printf "%*s\n" "${COLUMNS:-$(tput cols)}" '' | tr ' ' =
  printf "%s %s\n" "Total paket nekorpm yang akan dibuat  :" "$avail_pkg_count paket"
  printf "%s %s\n" "Total nama paket yang tidak diketahui :" "$none_pkg_count paket"
  while true; do
    read -p "Lanjutkan? [Y/n]: " confirm
    case "$confirm" in
      [Yy]|"" )
        make_nekorpm $fedora $arch $avail_pkg
        break
        ;;
      [Nn] )
        exit 1
        ;;
    esac
  done
}

prepare_root_temp ()
{
  mkdir -p "$root_temp"
  cp -r "$1" "$root_temp"
}

clean_root_temp ()
{
  rm -rf "$root_temp"
}

make_nekorpm ()
{
  local releasever=$1
  local rpmdb="/usr/share/nekorpm-pack/f$1-$arch"
  local skip=""
  clean_root_temp
  prepare_root_temp "$rpmdb"
  printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
  shift 2
  for i in "$@"
  do
    echo -e "Pembuatan paket nekorpm untuk $i dilakukan ...\n"
    download_package skip $i "$root_temp/f$releasever-$arch" $releasever
    packaging $skip $i $releasever
  done
  clean_root_temp
}

if [ $# -eq 0 ]; then
  echo -e "Nama paket belum disebutkan, minimal sebutkan 1 paket." \
          "\n\nPenggunaan\t: nekorpm-pack [--arch=arch] [--fedora=versi] app1 app2 ... appN" \
          "\nContoh 1\t: nekorpm-pack geany" \
          "\nContoh 2\t: nekorpm-pack geany texmaker gedit" \
          "\nContoh 3\t: nekorpm-pack --arch=x86_64 --fedora=23 geany gedit" \
          "\nContoh 4\t: nekorpm-pack --fedora=23 geany gedit" \
          "\nContoh 5\t: nekorpm-pack --arch=i686 geany gedit\n"
  exit 1;
else
  clear
  parse_option $@
fi
