#!/bin/bash

# MIT License
#
# Copyright (c) 2016 La Ode Muh. Fadlun Akbar
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# "temp_repo" must be declared in the main script
# and assigned with specific directory
temp_repo="/tmp/nekorpm"

# import function here
. /usr/share/nekorpm/functions/cleanup
. /usr/share/nekorpm/functions/check_package_corrupt
. /usr/share/nekorpm/functions/check_location
. /usr/share/nekorpm/functions/package_info
. /usr/share/nekorpm/functions/install_process

see_package_info ()
{
  rm_temp "$temp_repo"
  local location=''
  local check_corrupt=''
  package_path_info location
  if [[ "$location" != '' ]]; then
    package_corrupt_status check_corrupt "$location"
    extract_package_info "$location" $check_corrupt "$temp_repo"
    print_package_info
    rm_temp "$temp_repo"
    local back
    while true; do
      read -p "Cari nekorpm lain? [Y/n]: " back
      case "$back" in
        [Yy]|"" )
          see_package_info
          break
          ;;
        [Nn] )
          clear
          break
          ;;
      esac
    done
  fi
}

installation ()
{
  rm_temp "$temp_repo"
  local location=''
  local check_corrupt=''
  local user_confirm=''
  package_path_info location
  if [[ "$location" != '' ]]; then
    package_corrupt_status check_corrupt "$location"
    rm_temp "$temp_repo"
    install_confirm user_confirm
    extract_package_all $check_corrupt "$location" $user_confirm "$temp_repo"
    print_package_info "$temp_repo"
    install_process
    rm_temp "$temp_repo"
    ask_install_process_again installation
  fi
}

main ()
{
  echo "--------------------------------------"
  echo "-              nekorpm                -"
  echo "-      SINGE OFFLINE INSTALLER       -"
  echo "--------------------------------------"
  echo "-                                    -"
  echo "- 1. Install                         -"
  echo "- 2. Lihat Keterangan Suatu nekorpm   -"
  echo "- 3. Exit                            -"
  echo "-                                    -"
  echo -e "--------------------------------------\n"
  read -p "Pilihan [1-3]: " menu
  case "$menu" in
    1 )
      installation
      ;;
    2 )
      see_package_info
      ;;
    3 )
      rm_temp "$temp_repo"
      clear
      exit 0
      ;;
    * )
      clear
      ;;
  esac
}

clear
while true; do
  main
done
