#!/bin/bash

#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#   Copyrigth (C) La Ode Muh. Fadlun Akbar

repo_sementara="/tmp/onerpm"

bersihkan ()
{
  rm -rf $repo_sementara
}

paket_korup ()
{
  if [ ! `tar -tzf $lokasi_paket | grep -w "keterangan" | wc -l` -eq 0 ]; then
    if [ ! `tar -tzf $lokasi_paket | grep "\.rpm$" | wc -l` -eq 0 ]; then
      cek="ok";
    else
      echo -e "File .rpm tidak ditemukan dalam paket onerpm Anda." \
              "\nPastikan:\n - paket onerpm Anda tidak korup\n - " \
              "unduhlah paket onerpm dari sumber terpercaya\n";
      cek="no"
      bersihkan;
    fi
  else
    echo -e "Tidak dapat membaca file Keterangan\nFile tidak ditemukan\n" \
            "Pastikan:\n - paket onerpm Anda tidak korup\n - unduhlah" \
            "paket onerpm dari sumber terpercaya\n";
    cek="no"
    bersihkan;
  fi
}

lokasi ()
{
  while true; do
    if [ "$(rpm -q --qf %{NAME} zenity)" = "zenity" ]; then
      lokasi_paket=`zenity --file-selection --title="Pilih Paket ONERPM"`
    elif [ "$(rpm -q --qf %{NAME} kdialog)" = "kdialog" ]; then
      lokasi_paket=`kdialog --getopenfilename "$HOME" --title "Pilih Paket ONERPM"`
    else
      read -e -p "Lokasi paket onerpm [TAB untuk autocomplete]: " -i "/" lokasi_paket
    fi
    if [ -e $lokasi_paket ]; then
      if [ "${lokasi_paket: -7}" = ".onerpm" ]; then
        echo -e "\nPaket onerpm ditemukan!\n";
        case "$1" in
          instal)
            proses_pasang
            ;;
          info)
            info_paket $lokasi_paket
            ;;
        esac
        break;
      else
        if [[ "$lokasi_paket" == "" ]]; then
          echo -e "\nAnda belum memilih paket ONERPM\n"
        else
          echo -e "\nBukan paket onerpm\n";
        fi
        cari=true;
        while $cari; do
          read -p "Lanjutkan pencarian? [Y/n]: " lanjut_cari
          case "$lanjut_cari" in
            [Yy]|"" )
              break
              ;;
            [Nn] )
              clear
              cari=false
              ;;
          esac
        done
      fi
    else
      echo -e "\nLokasi tidak tersedia\n";
      cari=true;
      while $cari; do
        read -p "Lanjutkan pencarian? [Y/n]: " lanjut_cari
        case "$lanjut_cari" in
          [Yy]|"" )
            break
            ;;
          [Nn] )
            clear
            cari=false
            ;;
        esac
      done
    fi
    if [ "$cari" = "false" ]; then
      break;
    fi
  done
}

lihat_keterangan ()
{
  echo "-----------------------"
  echo "- Keterangan Aplikasi -"
  printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
  cat $repo_sementara/keterangan
  printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
}

proses_pasang ()
{
  bersihkan
  paket_korup
  if [ "$cek" = "ok" ]; then
    echo "Sedang melakukan pengekstrakan paket onerpm";
    rm -rf $repo_sementara;
    mkdir $repo_sementara;
    cp $lokasi_paket $repo_sementara/paket_onerpm;
    cd $repo_sementara;
    tar -xzf $repo_sementara/paket_onerpm;
    echo -e "Pengekstrakan selesai\n";
    lihat_keterangan;
    while true; do
      read -e -p "Lanjutkan instalasi? [Y/n]: " lanjut
      case "$lanjut" in
        [Yy]|"" )
          aplikasi=`grep -w Name $repo_sementara/keterangan | awk '{ print $3 }'`
          sudo dnf --allowerasing --disablerepo=\* \
                   --repofrompath $aplikasi,$repo_sementara --enablerepo=$aplikasi \
                   -y install $aplikasi \
                   /
          if [ $? -ne 0 ]; then
            echo -e "\nTerjadi kesalahan, proses instalasi dibatalkan.\n";
          else
            echo -e "Apikasi $aplikasi telah terinstall, selamat!\n";
          fi
          sleep 0.5
          bersihkan
          break
          ;;
        [Nn] )
          echo -e "\nInstalasi dibatalkan\n"
          bersihkan
          break
          ;;
      esac
    done
  fi
  while true; do
    read -p "Cari onerpm lain? [Y/n]: " kembali
    case "$kembali" in
      [Yy]|"" )
        lokasi instal
        break
        ;;
      [Nn] )
        clear
        break
        ;;
    esac
  done
}

dialog_pasang ()
{
  read -p "Install aplikasi ke sistem? [Y/n]: " pil
  case "$pil" in
    [Yy]|"" )
      lokasi instal
      ;;
    [Nn] )
      clear
      utama
      ;;
    * )
      dialog_pasang
      ;;
  esac
}

info_paket ()
{
  bersihkan
  paket_korup
  if [ "$cek" = "ok" ]; then
    mkdir -p $repo_sementara
    tar -xzf $1 -C $repo_sementara "keterangan";
    lihat_keterangan;
  fi
  while true; do
    read -p "Cari onerpm lain? [Y/n]: " kembali
    case "$kembali" in
      [Yy]|"" )
        lokasi info
        break
        ;;
      [Nn] )
        clear
        break
        ;;
    esac
  done
  bersihkan
}

utama ()
{
  echo "--------------------------------------"
  echo "-              ONERPM                -"
  echo "-      SINGE OFFLINE INSTALLER       -"
  echo "--------------------------------------"
  echo "-                                    -"
  echo "- 1. Install                         -"
  echo "- 2. Lihat Keterangan Suatu ONERPM   -"
  echo "- 3. Exit                            -"
  echo "-                                    -"
  echo -e "--------------------------------------\n"
  read -p "Pilihan [1-3]: " menu
  case "$menu" in
    1 )
      dialog_pasang
      ;;
    2 )
      lokasi info
      ;;
    3 )
      bersihkan
      clear
      exit 0
      ;;
  esac
}

clear
while true; do
  utama
done
